In [1]:
from fungiclef.seesaw_loss import seesaw_loss

from typing import Dict, Optional, Tuple, Union

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor

In [2]:
def seesaw_ce_loss(cls_score: Tensor,
                   labels: Tensor,
                   
                   avg_factor: Optional[int] = None) -> Tensor:
    
    return loss

In [12]:
seesaw_loss.SeesawLoss(num_classes=1605)

SeesawLoss()

In [13]:
from torch import Tensor
import numpy as np


In [14]:
class_distribution = torch.Tensor([1, 1, 1, 0, 1000])
logits = torch.Tensor(np.random.rand(15, 5))
y = torch.Tensor([np.random.choice(range(5)) for _ in range(15)]).long()

In [15]:
seesaw_ce_loss(logits, y, class_distribution, 5, 0.2, 0.8, 0.001)

TypeError: seesaw_ce_loss() takes from 2 to 3 positional arguments but 7 were given

In [40]:
F.one_hot(y, 5)

tensor([[0, 1, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1],
        [0, 0, 1, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 1]])

In [4]:
from torch.nn import BCEWithLogitsLoss

In [5]:
loss=BCEWithLogitsLoss(pos_weight=torch.Tensor([5]))

In [15]:
# 0 
pred_poison = 0 in [1, 2, 3]

pred_logit = torch.Tensor([1.5])


In [34]:

pred_logit = torch.Tensor([2])
pred_poison = 1 in [1, 2, 3]

poison_logit = pred_logit * ((-1) ** (1-pred_poison))

gt = torch.Tensor([1])
pred = poison_logit

loss(pred, gt)

tensor(0.6346)

In [21]:
pred_poison

False

In [13]:
(1 - pred_logit.sigmoid()).logit()

tensor([-1.5000])

In [7]:
gt = torch.Tensor([1])
pred = torch.Tensor([0])

loss(pred, gt)

tensor(3.4657)

In [6]:
gt = torch.Tensor([0, 0, 0, 0, 0])
pred = torch.Tensor([0, 0, 0, 0, 0])
loss(pred, gt)

tensor(0.6931)

In [35]:
from fungiclef.utils import get_poison_mapping


In [37]:
pmap = get_poison_mapping()

In [38]:
pmap

tensor([0., 0., 0.,  ..., 0., 0., 0.])

In [41]:
preds = torch.rand(64, 1717)

In [44]:
preds.argmax(1)

tensor([1239,  216,   70,  853,  192, 1440,  457,  523,  492,  650, 1017,  111,
        1503, 1203,  223,  444, 1698,  205,  352,  483, 1018,  756,  662,  342,
        1636, 1215,  758,  596,  900,    0,  660, 1653, 1136,   67,  528,  264,
        1202, 1428,  420,  968, 1534, 1447, 1091, 1568,  466, 1593,  886, 1078,
        1648,   73, 1640,  447, 1334,  189, 1269,  964, 1582,   70,  842,  338,
        1347,  943,  666,  550])

tensor([-0.9996, -0.9992, -0.9997, -0.9997, -0.9997, -0.9995, -0.9992, -0.9993,
        -0.9989, -0.9995, -0.9999, -0.9996, -0.9985, -0.9996, -0.9987, -0.9989,
        -0.9983, -0.9995, -0.9992, -0.9991, -0.9996, -0.9997, -0.9982, -0.9993,
        -0.9995, -0.9994, -0.9988, -0.9988, -0.9992, -0.9997, -0.9987, -0.9997,
        -0.9991, -0.9985, -0.9987, -0.9992, -1.0000, -0.9996, -0.9992,  0.9999,
        -0.9999, -0.9999, -0.9992, -0.9981, -1.0000, -0.9993, -0.9998, -0.9988,
        -0.9997, -0.9998, -0.9993, -0.9994, -1.0000, -0.9997, -1.0000, -0.9999,
        -0.9992, -0.9997,  1.0000, -0.9998, -0.9999, -0.9997, -0.9990, -0.9999])

In [58]:
m = preds.max(1)

In [62]:
preds.argmax(1)

tensor([1239,  216,   70,  853,  192, 1440,  457,  523,  492,  650, 1017,  111,
        1503, 1203,  223,  444, 1698,  205,  352,  483, 1018,  756,  662,  342,
        1636, 1215,  758,  596,  900,    0,  660, 1653, 1136,   67,  528,  264,
        1202, 1428,  420,  968, 1534, 1447, 1091, 1568,  466, 1593,  886, 1078,
        1648,   73, 1640,  447, 1334,  189, 1269,  964, 1582,   70,  842,  338,
        1347,  943,  666,  550])

In [60]:
m.indices

tensor([1239,  216,   70,  853,  192, 1440,  457,  523,  492,  650, 1017,  111,
        1503, 1203,  223,  444, 1698,  205,  352,  483, 1018,  756,  662,  342,
        1636, 1215,  758,  596,  900,    0,  660, 1653, 1136,   67,  528,  264,
        1202, 1428,  420,  968, 1534, 1447, 1091, 1568,  466, 1593,  886, 1078,
        1648,   73, 1640,  447, 1334,  189, 1269,  964, 1582,   70,  842,  338,
        1347,  943,  666,  550])

In [46]:
y_pred_poison_cls = pmap[preds.argmax(1)]
y_pred_unknown_cls = preds.argmax(1) >= 1604

preds.max(1).values * ((-1) ** (1-pmap[preds.argmax(1)]))

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [ ]:
poison_logit = pred_logit * ((-1) ** (1-pred_poison))
